name: CI/CD Pipeline for Angular on Azure

on:
    push:
        branches: [main, develop, feature/*]

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Install Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: "21.5"

            - name: Install Angular CLI
              run: npm install -g @angular/cli

            - name: Install Dependencies and Build
              run: |
                  npm install
                  ng build

            - name: Run Tests
              run: ng test --watch=false --browsers=ChromeHeadless

            - name: Deploy to Azure
              if: github.ref == 'refs/heads/main'
              uses: azure/webapps-deploy@v2
              with:
                  app-name: "trelloFront"
                  publish-profile: ${{ secrets.AzurePublishProfile }}
                  package: "./dist/your-app"
